In [1]:
import numpy as np
import matplotlib.pyplot as plt

In [2]:
p1 = 0.6
p2 = 0.4

In [3]:
odds_p1 = (p1 / (1 - p1))
odds_p1

1.4999999999999998

In [4]:
odds_p2 = (p2 / (1 - p2))
odds_p2

0.6666666666666667

In [5]:
log_odds_p1 = np.log(odds_p1)
log_odds_p1

0.4054651081081642

In [6]:
log_odds_p2 = np.log(odds_p2)
log_odds_p2

-0.4054651081081643

In [7]:
# Define the sigmoid function (inverse logit)
def sigmoid(logit):
    return 1 / (1 + np.exp(-logit))

sigmoid(log_odds_p1)

0.6

In [8]:
sigmoid(log_odds_p2)

0.4

In [12]:
def softmax(z):
    # exp_z = np.exp(z - np.max(z, axis=1, keepdims=True))    
    exp_z = np.exp(z) 
    print(exp_z)
    
    return exp_z / (1 + exp_z.sum(axis=1, keepdims=True))

In [13]:
z = np.array([[log_odds_p1, log_odds_p2]])
z

array([[ 0.40546511, -0.40546511]])

In [14]:
softmax(z)

[[1.5        0.66666667]]


array([[0.69230769, 0.30769231]])